ourwedding/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from weddingapp.views import home_view, gifts_view, hotels_view

urlpatterns = [
    url(r'^$', home_view, name='home'),
    url(r'^rsvp/', include('weddingapp.rsvp_urls')),
    url(r'^faq/', include('weddingapp.faq_urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^gifts/', gifts_view, name='gifts'),
    url(r'^hotels/', hotels_view, name='hotels'),
]

weddingapp/models.py
from __future__ import unicode_literals

import random
import string

from django.core.validators import RegexValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# needed for Python 2
# from weddingapp.utils import code_generator


def code_generator(size=6, chars=string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


# RSVP!
@python_2_unicode_compatible
class Invite(models.Model):
    # Code to identify invites by
    code = models.CharField(max_length=6, default=code_generator(4), unique=True)
    # i.e. Shambrook Family
    group_name = models.CharField(max_length=200)
    # number of people in this invite (i.e. husband and wife get one invite)
    group_count = models.IntegerField()
    email = models.EmailField(blank=True, null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="")
    phone_number = models.CharField(validators=[phone_regex], max_length=12)
    song_requests = models.CharField(max_length=250, null=True, blank=True)
    rsvp_completed = models.NullBooleanField(default=False, editable=False)

    def __str__(self):
        return self.group_name


@python_2_unicode_compatible
class Guest(models.Model):
    invite = models.ForeignKey(Invite, on_delete=models.CASCADE)
    # i.e. Billy Shambrook
    guest_name = models.CharField(max_length=200)
    diet = models.CharField(max_length=250, null=True, blank=True)
    transport = models.NullBooleanField(default=False)
    attending = models.NullBooleanField(default=False)

    def __str__(self):
        return self.guest_name


GIFT_CATEGORIES = (
    ('kitchen', 'Kitchen'),
    ('electric', 'Electric Items'),
    ('crockery', 'Crockery'),
    ('glass', 'Glasses'),
    ('cutlery', 'Cutlery'),
    ('knives', 'Knives'),
    ('pots_pans', 'Pots and Pans'),
    ('linens', 'Linens'),
    ('house', 'Houseware'),
    ('other', 'Other')
)


@python_2_unicode_compatible
class Gift(models.Model):
    item = models.CharField(max_length=200)
    quantity = models.IntegerField(blank=True, null=True)
    actual = models.CharField(
        max_length=200,
        choices=(('exact', 'Exact'), ('similar', 'Similar')),
        default='exact',
        blank=True
    )
    category = models.CharField(
        max_length=200,
        choices=GIFT_CATEGORIES,
        default='kitchen'
    )
    url = models.URLField(blank=True, max_length=200)

    def __str__(self):
        return self.item


class Hotel(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    postcode = models.CharField(max_length=10)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="")
    phone_number = models.CharField(validators=[phone_regex], max_length=12, blank=True)
    google_link = models.URLField(blank=True, max_length=200)
    website_link = models.URLField(blank=True, max_length=200)

weddingapp/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from weddingapp.models import Guest


class ExtraForm(forms.ModelForm):
    diet = forms.CharField(max_length=128,
                           help_text=_("Please enter any dietary requirements for :"),
                           required=False,
                           widget=forms.TextInput(attrs={'class': 'form-control'})
                           )

    transport = forms.BooleanField(
        initial=False,
        help_text=_("Would /guest name/ be interested in transport from the church to the reception?"),
        required=False
    )

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Guest
        fields = ('diet', 'transport')

weddingapp/views.py
import urllib

from django.conf import settings
from django.forms import inlineformset_factory
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponseRedirect, Http404
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.utils import translation
from django.utils.translation import check_for_language
from pip._vendor.requests.packages.urllib3.util import url

from weddingapp.forms import ExtraForm
from .models import Invite, Guest, Gift, Hotel


siteLanguages = (('en', 'English'), ('da', 'Danish'))


def set_language(request):
    next = request.META.get('HTTP_REFERER', None)
    response = HttpResponseRedirect(next)

    if request.method == 'GET':
        lang_code = request.GET.get('language', None)
        if lang_code and check_for_language(lang_code):
            if hasattr(request, 'session'):
                request.session['django_language'] = lang_code
            else:
                response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang_code)
            translation.activate(lang_code)
    return reverse()


def faq_index(request):
    # automatic redirect (could've done this in .htaccess but meh)
    return HttpResponseRedirect('practical')


def faq_practical(request):
    context = {
        'page': 'practical'
    }
    return render(request, 'weddingapp/practical.html', context)


def faq_cultural(request):
    return render(request, 'weddingapp/cultural.html', {'page': 'cultural'})


def get_invite(code):
    # Expects code to find invite with
    try:
        invite = Invite.objects.get(code=code)
    except Invite.DoesNotExist:
        return None

    return invite


def check_invite(invite):
    if invite is None:
        # if the invite doesn't exist, return a 404
        raise Http404("Invite does not exist")

    if invite.rsvp_completed:
        # if the invite has been completed, redirect to the finish page
        # return HttpResponseRedirect(reverse('weddingapp:finish', args=(invite.code,)))
        # finish_view(request, invite.code)
        return redirect('weddingapp:finish', code=invite.code)


def home_view(request):
    return render(request, 'weddingapp/home.html', {})


def gifts_view(request):
    giftlist = Gift.objects.order_by('category', 'item').all()

    return render(request, 'weddingapp/giftlist.html', {'giftlist': giftlist})


def hotels_view(request):
    hotels_list = Hotel.objects.all()

    for hotel in hotels_list:
        link = construct_maps_link(hotel.postcode)
        hotel.static_map_link = link

    return render(request, 'weddingapp/hotels.html', {'hotels_list': hotels_list})


def construct_maps_link(postcode):
    maps_link = "http://maps.googleapis.com/maps/api/staticmap?"

    maps_link += "key=AIzaSyBg35fbhMM1PUchxu3-U0otlG0BL-Tgryc"
    maps_link += "&autoscale=false"
    maps_link += "&size=520x160"
    maps_link += "&maptype=roadmap"
    maps_link += "&format=png"
    maps_link += "&visual_refresh=true"

    label = "&markers=size:mid%7Ccolor:0x04ca0e%7Clabel:%7C" + postcode
    label += "&markers=size:mid%7Ccolor:0xff0000%7Clabel:%7CCM13 3SW"

    label = label.replace(" ", "+")

    maps_link += label

    return maps_link


def index_view(request):
    if request.method == 'POST':
        code = request.POST['code']
        requested_invite = get_invite(code)

        if requested_invite is None:
            return render(request, 'weddingapp/index.html', {
                'does_not_exist': True,
                'code': code
            })
        else:
            return HttpResponseRedirect(reverse('weddingapp:attend', args=(code,)))

    return render(request, 'weddingapp/index.html', {})


def welcome_view(request, code):
    invite = get_invite(code)
    check_invite(invite)

    context = {
        'invite': invite
    }
    return render(request, 'weddingapp/welcome.html', context)


def attend_view(request, code):
    invite = get_invite(code)
    if request.method == 'POST':
        try:
            # loop through each guest and assign its attendance
            # get all guests that were shown, then all guests sent in the POST
            # make a comparison to find who's going and who's not
            guests = invite.guest_set.all()
            guests_attending = request.POST.getlist('attend')

            for guest in guests:
                guest.attending = guest.guest_name in guests_attending
                guest.save()
        except (KeyError, Invite.DoesNotExist):
            # Redisplay the form.
            return render(request, 'weddingapp/attend.html', {
                'invite': invite,
                'error_message': "This invite does not exist.",
            })
        else:
            # Always return an HttpResponseRedirect after successfully dealing
            # with POST data. This prevents data from being posted twice if a
            # user hits the Back button.
            # go to Extras page
            return HttpResponseRedirect('extra')
    else:
        return render(request, 'weddingapp/attend.html', {
            'invite': invite,
        })


def extra_view(request, code):
    # Get the specific invite
    invite = get_invite(code)
    check_invite(invite)

    # Get the context from the request.
    context = RequestContext(request)

    # Store guests attending object
    guests_attending = invite.guest_set.filter(attending=True, invite=invite)

    # Create the formset for each Guest
    GuestFormset = inlineformset_factory(Invite, Guest,
                                         form=ExtraForm,
                                         fields=('diet', 'transport'),
                                         extra=0,
                                         can_delete=False)

    if request.method == "POST":
        formset = GuestFormset(request.POST, request.FILES,
                               instance=invite,
                               queryset=Guest.objects.filter(attending=1))

        if formset.is_valid():
            # Save the data to the database.
            formset.save()

            # Go to Confirm page
            return HttpResponseRedirect('confirm')
        else:
            # The supplied form contained errors - just print them to the terminal for now
            print formset.errors

    if guests_attending.count() > 0:
        formset = GuestFormset(instance=invite, queryset=Guest.objects.filter(attending=1))

        # Return the view
        return render_to_response('weddingapp/extra.html', {
            'GuestForm': formset,
            'invite': invite,
            'guests_attending': guests_attending,
            'errors': formset.errors
        }, context)
    else:
        # Since there's no guests to create a form for, return Confirm view
        return render(request, 'weddingapp/confirm.html', {
            'invite': invite,
        })


def confirm_view(request, code):
    invite = get_invite(code)
    check_invite(invite)

    return render(request, 'weddingapp/confirm.html', {
        'invite': invite,
    })


def finish_view(request, code):
    invite = get_invite(code)

    if invite is not None and invite.rsvp_completed is False:
        invite.rsvp_completed = True
        invite.save()

    return render(request, 'weddingapp/finish.html', {
        'invite': invite,
    })

weddingapp/templates/weddingapp/attend.html
{% extends "layout_rsvp.html" %}
{% load i18n %}

{% block content %}
    {% if invite %}
        <p>{% trans "Your code has been accepted! As stated on the invitation, please complete your RSVP by August 15th 2016." %}</p>

        <p>{% trans "We are eagerly awaiting our big day, and we sincerely hope that you will be able to share this special occasion with us." %}</p>
        <p>
            {% trans "Below is a list of the guests on your invitation; please untick those who are unable to attend." %}</p>
        <form action="{% url 'weddingapp:attend' invite.code %}" method="post">
            {% csrf_token %}
            {% for guest in invite.guest_set.all %}
                <div>
                    <input type="checkbox" name="attend" id="choice{{ forloop.counter }}"
                           value="{{ guest.guest_name }}"
                           {% if guest.attending %}checked="checked"{% endif %}/>
                    <label for="choice{{ forloop.counter }}">{{ guest.guest_name }}</label>
                </div>
            {% endfor %}

            <div class="row flex-justify-end m-t-2">
                <div class="col-sm-4 col-xs-12">
                    <button type="submit" class="btn btn-wedding-coral btn-lg btn-block">{% trans "Continue" %}</button>
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}

weddingapp/templates/weddingapp/confirm.html
{% extends "layout_rsvp.html" %}
{% load i18n %}

{% block content %}
    {% if invite %}
        <p>{% trans "Before completing your RSVP, please ensure the information you have provided is correct. Below is an overview of the details entered." %}</p>

        <div class="row m-b-2 m-t-2">
            {% for guest in invite.guest_set.all %}
                <div class="col-sm-6">
                    <h5>{{ guest.guest_name }}</h5>

                    <dl class="dl-horizontal">
                        <dt class="col-sm-3 m-l-1">{% trans "Attending" %}:</dt>
                        <dd class="col-sm-9 m-l-1">{{ guest.attending|yesno:_("Yes,No") }}</dd>

                        {% if guest.attending == 1 %}
                            <dt class="col-sm-3 m-l-1">{% trans "Dietary Requirements" %}:</dt>
                            <dd class="col-sm-9 m-l-1">{{ guest.diet }}</dd>

                            <dt class="col-sm-3 m-l-1">{% trans "Interest In Transport" %}:</dt>
                            <dd class="col-sm-9 m-l-1">{{ guest.transport|yesno:_("Yes,No") }}</dd>
                        {% endif %}
                    </dl>
                </div>
            {% endfor %}
        </div>

        <div class="row">
            <div class="col-sm-5 m-b-3">
                <p>{% trans "If any of the above details are incorrect, you can go back and amend them." %}</p>

                <div class="row m-t-2">
                    <div class="col-sm-4 col-xs-12">
                        <a href="{% url 'weddingapp:attend' invite.code %}"
                           class="btn btn-wedding-blue btn-lg">{% trans "Go Back" %}</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-5 col-sm-offset-2 text-md-right m-b-3">
                <p>{% trans "If all of the above details are correct, click below to complete your RSVP." %}</p>

                <div class="row flex-justify-end m-t-2">
                    <div class="col-sm-4 col-xs-12">
                        <a href="{% url 'weddingapp:finish' invite.code %}"
                           class="btn btn-wedding-coral btn-lg btn-block">{% trans "Complete RSVP" %}</a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

weddingapp/templates/weddingapp/cultural.html
{% extends "layout_faq.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}

    <h5><strong>{% trans "Wedding traditions" %}</strong></h5>
    <p>{% trans "There are a range of curious and entertaining traditions connected to a wedding reception in Denmark. We have outlined these below so our guests hopefully won't be (too) surprised!" %}</p>

    <h5><strong>{% trans "Kissing rituals" %}</strong></h5>
    <p>{% trans "When the guests clink their cutlery on their plates, the newlyweds must stand on their chairs and kiss. If the guests stamp their feet on the floor, they must climb under the table and kiss. " %}</p>

    <h5><strong>{% trans "Kissing rituals – when the newlyweds leave the table" %}</strong></h5>
    <p>{% trans "When either of the newlyweds leave the table, guests of the same gender can run up to give the person left a cheeky kiss on the cheek! i.e. if the bride leaves the table, the female guests get to run up and kiss the groom, and vice versa." %}</p>

    <h5><strong>{% trans "Cutting the brides veil" %}</strong></h5>
    <p>{% trans "After the first dance, the bride's veil is cut or torn into pieces. According to superstition, the more it is ruined, the happier she will be in her marriage and guests should take a piece home with them as this will bring them luck." %}</p>

    <h5><strong>{% trans "Cutting the grooms socks" %}</strong></h5>
    <p>{% trans "Before leaving the reception, the male guests must remove the groom's socks and cut off the toes. This is to signify that he is no longer on “frierfødder”, which translates to “proposing feet” - essentially that he is no longer courting!" %}</p>

    <h5><strong>{% trans "Brudevalsen – the first dance" %}</strong></h5>
    <p>{% trans "The traditional first dance is called “Brudevalsen”, which translates to “The Bride Waltz”. The bride and groom dance with their guests surrounding them, who after a minute or so begin to close in on the couple, until they are no longer able to move. For a visual image of what this will look like, this is a video of the royal wedding in 2004:" %}
        <a href="https://www.youtube.com/watch?v=yVQarqT61ss">https://www.youtube.com/watch?v=yVQarqT61ss</a></p>

    <div id="formal-pictures">
        <h5><strong>{% trans "Formal pictures" %}</strong></h5>
        <p>{% trans "The Danish tradition is to take portraits of the couple and the English tradition is to take photographs of many family constellations. If we ask you to jump into a formal picture, please don't be taken aback!" %}</p>
    </div>

    <div id="confetti-rice">
        <h5><strong>{% trans "Confetti or rice" %}</strong></h5>
        <p>{% trans "Upon leaving the church, it is Danish tradition to throw rice at the newlyweds, which they supply. It is English tradition to throw confetti, which you supply. We have decided to go with rice." %}</p>
    </div>

    <div id="no-songs">
        <h5><strong>{% trans "Songs for an occasion" %}</strong></h5>
        <p>{% trans "While we appreciate festive additions to our reception, we're not keen on the Danish tradition of writing songs and we're also mindful that half our guests aren't Danish. If you would like to do something nice for us at the reception, why not prepare a speech?" %}</p>
    </div>

{% endblock %}

weddingapp/templates/weddingapp/extra.html
{% extends "layout_rsvp.html" %}
{% load i18n %}

{% block content %}
    {% if invite %}
        <p>{% trans "We would like to ask you to provide a few details so that we can meet any additional needs you may have." %}</p>

        <p>{% trans "As we are aware that a portion of our guests do not live locally, we will potentially provide transport between the church and the reception venue, depending on the amount of guests who require this." %}</p>

        {{ form_errors }}

        <form method="post" action="">
            {% csrf_token %}
            {{ GuestForm.management_form }}
            {% for form in GuestForm %}

                <div class="m-b-2">
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    <fieldset class="form-group">
                        {{ form.diet.errors }}
                        <label for="{{ form.diet.id_for_label }}">
                            {% blocktrans with guest=form.instance.guest_name %}Please enter any dietary requirements for {{ guest }}{% endblocktrans %}:
                        </label>
                        {{ form.diet }}
                    </fieldset>

                    <fieldset class="checkbox">
                        {{ form.transport.errors }}
                        <label for="{{ form.transport.id_for_label }}">
                            {{ form.transport }} {% blocktrans with guest=form.instance.guest_name %}Would {{ guest }} be interested in transport from the church to the reception?{% endblocktrans %}
                        </label>
                    </fieldset>

                    <hr/>
                </div>
            {% endfor %}

            <div class="row flex-justify-end m-t-2">
                <div class="col-sm-4 col-xs-12">
                    <button type="submit" class="btn btn-wedding-coral btn-lg btn-block">{% trans "Continue" %}</button>
                </div>
            </div>
        </form>
    {% endif %}
{% endblock %}

weddingapp/templates/weddingapp/faq.html
{% extends "layout_faq.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}

    <h3></h3>

{% endblock %}

weddingapp/templates/weddingapp/finish.html
{% extends "layout_rsvp.html" %}

{% load staticfiles %}
{% load i18n %}

{% block content %}
    <h2>{% trans "Thank you!" %}</h2>
    <p>{% trans "Thank you for completing your RSVP! Feel free to explore our website, and check back as we will continue to update it with information and relevant details. See you next June! - Joseph and Louise" %}</p>

    <div class="m-t-2 m-b-2 text-xs-center">
        <a href="/" class="btn btn-wedding-coral btn-lg">
            {% trans "Go to our website" %}</a>
    </div>

    <img src="{% static "dist/img/us-min-sized.png" %}" class="img-fluid m-b-3 m-t-1"
         alt="{% trans "An image of Joseph and Louise on Chelsea Embankment in London" %}">
{% endblock %}

weddingapp/templates/weddingapp/giftlist.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block header-class %}small-header{% endblock %}
{% block nav-gifts %}active{% endblock %}

{% block layout %}

    <div class="container m-b-3">
        <div class="row">
            <div class="col-md-offset-1 col-lg-offset-2 col-lg-8 col-md-10 col-sm-12 col-xs-12">
                <p>{% trans "Our gift list is below should you wish to buy us a wedding gift. However, please do not feel obliged to buy us a gift at all; all we really want for our special day is to have you there to celebrate with." %}</p>

                <p>{% trans "For some items, the attached link is the exact item we would like and for some the link is a suggestion. We have indicated which is applicable for each item." %}</p>

                <p>{% trans "To avoid duplicate gifts and returns, we kindly ask guests to contact Rachel Shambrook on rachel.shambrook@icloud.com before purchasing a gift, to check if the gift you intend to purchase has already been purchased." %}</p>
                <table class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>{% trans "Item" %}</th>
                            <th>{% trans "Category" %}</th>
                            <th>{% trans "Quantity" %}</th>
                            <th>{% trans "Actual Item?" %}</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for gift in giftlist %}
                            <tr>
                                <td>{{ gift.item }}</td>
                                <td>{{ gift.get_category_display }}</td>
                                <td>{% if gift.quantity and gift.quantity > 0 %}{{ gift.quantity }}{% endif %}</td>
                                <td>{{ gift.get_actual_display }}</td>
                                <td>
                                    {% if gift.url and gift.quantity > 0 %}
                                        <a href="{{ gift.url }}" target="_blank" rel="nofollow">{% trans "Link" %}</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

weddingapp/templates/weddingapp/home.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block nav-home %}active{% endblock %}
{% block header-class %}m-b-0{% endblock %}

{% block layout %}

    <section class="section-about-wedding">
    <div class="container">
        <div class="section-title text-xs-center">
            <h2>{% trans "The Wedding" %}</h2>
        </div>
        <div class="row text-xs-center m-t-3">
            <div class="col-lg-offset-2 col-lg-4 col-md-6 m-b-2">
                <div class="m-b-1">
                    <img src="{% static "dist/img/wedding-rings.svg" %}" alt="Wedding rings" width="80">
                </div>
                <h5>{% trans "The ceremony will take place from 2:30pm at St. George's Church, Beckenham, Kent." %}</h5>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="m-b-1">
                    <img src="{% static "dist/img/toast.svg" %}" alt="Glasses toasting" width="80">
                </div>
                <h5>{% trans "The reception and dinner will take place at The Old Rectory, Brentwood, Essex." %}</h5>
            </div>
        </div>
    </div>
</section>

<section class="section-links">
    <div class="container">
        <div class="row">
            <div class="col-lg-offset-2 col-lg-4 col-md-6 col-sm-6 col-xs-12 text-xs-center m-b-2">
                <h2 class="m-b-1">{% trans "Got Questions?" %}</h2>
                <a href="/faq" class="btn btn-lg btn-wedding-coral">{% trans "Go to FAQs" %}</a>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 text-xs-center">
                <h2 class="m-b-1">{% trans "Need to RSVP?" %}</h2>
                <a href="/rsvp" class="btn btn-lg btn-wedding-coral">{% trans "Go to RSVP site" %}</a>
            </div>
        </div>
    </div>
</section>

<section class="section-contact">
    <div class="container">
        <div class="section-title text-xs-center">
            <h2>{% trans "Get in touch" %}</h2>
        </div>
        <div class="row text-xs-center m-t-3">
            <a href="http://www.google.com/recaptcha/mailhide/d?k=01_r--5p3jq1yieuawqbWXdw==&amp;c=hzlMjzYWn28NHdWFV6ZN_tmtVn9LeWQWw-ffPK4cgQ0="
               onclick="window.open('http://www.google.com/recaptcha/mailhide/d?k\x3d01_r--5p3jq1yieuawqbWXdw\x3d\x3d\x26c\x3dhzlMjzYWn28NHdWFV6ZN_tmtVn9LeWQWw-ffPK4cgQ0\x3d', '', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=300'); return false;"
               title="Reveal this e-mail address" class="col-lg-offset-2 col-lg-4 col-md-6 col-sm-6 col-xs-12 m-b-2">
                <div class="m-b-1">
                    <img src="{% static "dist/img/e-mail-envelope.svg" %}" alt="Envelope" width="80">
                </div>
                <h5>Email</h5>
            </a>

            <a href="https://www.facebook.com/WinterJoey" target="_blank" class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                <div class="m-b-1">
                    <img src="{% static "dist/img/thumb-up.svg" %}" alt="Thumbs up" width="80">
                </div>
                <h5>Facebook</h5>
            </a>
        </div>
    </div>
</section>

<section class="section-final-photo"></section>

<footer class="fs">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p class="m-b-0 text-xs-center">
                    <small>
                        {% blocktrans %}Our beautiful photos are by
                            <a href="http://www.bennicarolweddingphotography.com/">Benni Carol Photography</a>
                            .{% endblocktrans %}
                    </small>
                </p>
                <p class="m-b-0 text-xs-center">
                    <small>
                        {% blocktrans %}Website design and development by
                            <a href="http://www.josephshambrook.com">Joseph Shambrook</a> (the
                            groom!).{% endblocktrans %}
                    </small>
                </p>
                <p class="m-b-0 text-xs-center">
                    <small>Icons made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a
                            href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed by <a
                            href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0"
                            target="_blank">CC 3.0 BY</a>.
                    </small>
                </p>
            </div>
        </div>
    </div>
</footer>

{% endblock %}

weddingapp/templates/weddingapp/hotels.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block header-class %}small-header{% endblock %}
{% block nav-hotels %}active{% endblock %}

{% block layout %}

    <div class="container m-b-3">
        <div class="row">

            {% for hotel in hotels_list %}
                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                    <div class="card">
                        {% if hotel.static_map_link %}
                            <img class="card-img-top img-fluid" src="{{ hotel.static_map_link }}" alt="Map to
{{ hotel.name }}">
                        {% endif %}
                        <div class="card-block">
                            <h4 class="card-title">{{ hotel.name }}</h4>
                            <div class="card-text">
                                {% if hotel.address %}
                                    <p>{{ hotel.address }}</p>
                                {% endif %}

                                {% if hotel.phone_number %}
                                    <p>{{ hotel.phone_number }}</p>
                                {% endif %}
                            </div>
                            {% if hotel.google_link %}
                                <a href="{{ hotel.google_link }}" class="btn btn-wedding-coral">Google Maps</a>
                            {% endif %}
                            {% if hotel.website_link %}
                                <a href="{{ hotel.website_link }}" class="btn btn-wedding-coral">Website</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

weddingapp/templates/weddingapp/index.html
{% extends "layout_rsvp.html" %}
{% load i18n %}

{% block content %}
    <p>{% trans "Welcome to our RSVP website. Please enter the code on your invitation below to continue." %}</p>

    <form action="{% url 'weddingapp:index' %}" method="post">
        {% csrf_token %}
        <div class="form-group {% if does_not_exist %}has-danger{% endif %}">

            {% if does_not_exist %}
                <label class="form-control-label" for="code">The code you entered does not exist. Please try another code or get in touch if there's a problem.</label>
            {% endif %}

            <input type="text" name="code" id="code" class="form-control" value="{{ code }}"
                   placeholder="{% trans "Enter your code here" %}"/>

        </div>

        <div class="row flex-justify-end m-t-2">
            <div class="col-sm-4 col-xs-12">
                <button type="submit" class="btn btn-wedding-coral btn-lg btn-block">{% trans "Continue" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

weddingapp/templates/weddingapp/menu.html
<div>menu!</div>